# Generated by Django 2.1.7 on 2019-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='off_id',
            field=models.TextField(),
        ),
    ]
