# Generated by Django 2.1.7 on 2019-04-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190411_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='salt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sugars',
            field=models.FloatField(null=True),
        ),
    ]
