# Generated by Django 2.1.7 on 2019-04-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190402_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/c/c5/Foods.jpg', unique=True),
        ),
    ]
